trigger:
  branches:
    # Branch names are case senititve
    include:
      - main
  paths:
    # Triggers only on modification to contents of assignments directory
    include:
      - Assignments/*
    exclude:
      - Assignments/README.MD

variables:
  rootFolder: '"$(System.DefaultWorkingDirectory)/"'
  # Definition location references management group of the initiative (tenant root group for delivery)
  definitionLocation: "MSMCSAIRS6121349"
  folderName: "Assignments"
  # Reference to service connections of the different environments
  prodServiceConnection: "policy-management-spn"
  Assignments: "febd0533-8e55-448f-b837-bd0e06f16469"

stages:
  - stage: PROD
    displayName: "PROD"
    condition: contains(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - deployment: PROD_Deployment
        environment: SCaC-PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PowerShell@2
                  displayName: "Check file diff"
                  condition: ne(variables['Build.Reason'], 'Manual')
                  inputs:
                    filePath: "Libraries/Tools/Misc/checkDiff.ps1"
                    arguments: "-folderName $(folderName)
                      -defRootFolder $(rootFolder)"

                - task: AzurePowerShell@4
                  displayName: "Create Assignments"
                  inputs:
                    azureSubscription: $(prodServiceConnection)
                    ScriptPath: "Libraries/Tools/Az/Create-PolicyAssignment.ps1"
                    ScriptArguments: "-rootFolder $(rootFolder)
                      -assignmentNames $(Assignments)
                      -definitionLocation $(definitionLocation)"
                    azurePowerShellVersion: LatestVersion
                  condition: and(succeeded(), ne(variables['Assignments'], ''))
